#!/usr/bin/perl -w -- 
# generated by wxGlade 0.4.1 on Sun Oct 22 22:44:38 2006
# To get wxPerl visit http://wxPerl.sourceforge.net/

use Wx 0.15 qw[:allclasses];
use strict;
use Wx::Grid;

package MyFrame2;

use Wx qw[:everything];
use base qw(Wx::Frame);
use strict;

sub new {
	my( $self, $parent, $id, $title, $pos, $size, $style, $name ) = @_;
	$parent = undef              unless defined $parent;
	$id     = -1                 unless defined $id;
	$title  = ""                 unless defined $title;
	$pos    = wxDefaultPosition  unless defined $pos;
	$size   = wxDefaultSize      unless defined $size;
	$name   = ""                 unless defined $name;

# begin wxGlade: MyFrame2::new

	$style = wxDEFAULT_FRAME_STYLE 
		unless defined $style;

	$self = $self->SUPER::new( $parent, $id, $title, $pos, $size, $style, $name );
	$self->{text_ctrl_1} = Wx::TextCtrl->new($self, -1, "", wxDefaultPosition, wxDefaultSize, );
	$self->{button_1} = Wx::Button->new($self, -1, "Browse");
	$self->{button_2} = Wx::Button->new($self, -1, "Search");
	$self->{grid_1} = Wx::Grid->new($self, -1);

	$self->__set_properties();
	$self->__do_layout();

	Wx::Event::EVT_BUTTON($self, $self->{button_2}->GetId, \&do_lib);

# end wxGlade
	return $self;

}


sub __set_properties {
	my $self = shift;

# begin wxGlade: MyFrame2::__set_properties

	$self->SetTitle("Salami");
	$self->SetSize(Wx::Size->new(522, 321));
	$self->{text_ctrl_1}->SetSize(Wx::Size->new(400, -1));
	$self->{grid_1}->CreateGrid(10, 3);
	$self->{grid_1}->SetSelectionMode(wxGridSelectCells);

# end wxGlade
}

sub __do_layout {
	my $self = shift;

# begin wxGlade: MyFrame2::__do_layout

	$self->{grid_sizer_1} = Wx::FlexGridSizer->new(3, 1, 0, 0);
	$self->{grid_sizer_2} = Wx::FlexGridSizer->new(1, 2, 0, 0);
	$self->{grid_sizer_2}->Add($self->{text_ctrl_1}, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_2}->Add($self->{button_1}, 0, wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_1}->Add($self->{grid_sizer_2}, 1, wxEXPAND, 0);
	$self->{grid_sizer_1}->Add($self->{button_2}, 0, wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 0);
	$self->{grid_sizer_1}->Add($self->{grid_1}, 1, wxEXPAND, 0);
	$self->SetAutoLayout(1);
	$self->SetSizer($self->{grid_sizer_1});
	$self->Layout();

# end wxGlade
}

sub do_lib {
	my ($self, $event) = @_;
# wxGlade: MyFrame2::do_lib <event_handler>

	warn "Event handler (do_lib) not implemented";
	$event->Skip;

# end wxGlade
}


# end of class MyFrame2

1;

1;

package main;

unless(caller){
	local *Wx::App::OnInit = sub{1};
	my $app = Wx::App->new();
	Wx::InitAllImageHandlers();

	my $frame_3 = MyFrame2->new();

	$app->SetTopWindow($frame_3);
	$frame_3->Show(1);
	$app->MainLoop();
}
