# 8 December 2001
# rcsid = $Id: Makefile,v 1.1 2002/02/07 06:32:18 torda Exp $

all:
	echo "Happy in src/Simplex"

clean:
	-rm -f *~
	-rm -f *.o
	-rm -f *.ln
	-rm -f Makefile.$(LIBNAME)
	-rm -f $(WURSTLIB)
	-rm -f depend
	-rm -f TAGS
